// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYO1DNh9gLMtH5g_IsDRl2W32L1yU12Uo',
    appId: '1:1099215340735:web:4ffe0cacd1ad2ae38d720a',
    messagingSenderId: '1099215340735',
    projectId: 'finances-455c0',
    authDomain: 'finances-455c0.firebaseapp.com',
    storageBucket: 'finances-455c0.firebasestorage.app',
    measurementId: 'G-Z42P6MFR68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA1zJOJG3C0psSe3GUWogOMP463cs2sXU',
    appId: '1:1099215340735:android:2157280cbcdc20858d720a',
    messagingSenderId: '1099215340735',
    projectId: 'finances-455c0',
    storageBucket: 'finances-455c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA16IlQHYdIFnFShs1bWT3VCov0USG_N_o',
    appId: '1:1099215340735:ios:1bd8209ddc31c2728d720a',
    messagingSenderId: '1099215340735',
    projectId: 'finances-455c0',
    storageBucket: 'finances-455c0.firebasestorage.app',
    iosBundleId: 'com.example.finance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA16IlQHYdIFnFShs1bWT3VCov0USG_N_o',
    appId: '1:1099215340735:ios:1bd8209ddc31c2728d720a',
    messagingSenderId: '1099215340735',
    projectId: 'finances-455c0',
    storageBucket: 'finances-455c0.firebasestorage.app',
    iosBundleId: 'com.example.finance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYO1DNh9gLMtH5g_IsDRl2W32L1yU12Uo',
    appId: '1:1099215340735:web:65a603fa780660ef8d720a',
    messagingSenderId: '1099215340735',
    projectId: 'finances-455c0',
    authDomain: 'finances-455c0.firebaseapp.com',
    storageBucket: 'finances-455c0.firebasestorage.app',
    measurementId: 'G-19JNNK38VX',
  );
}
